// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqzzEyHE8SfGHbo98jhT7awFlA77fxexM',
    appId: '1:64115782291:web:d8244112b1b716a61d9366',
    messagingSenderId: '64115782291',
    projectId: 'notification-demo-c82e6',
    authDomain: 'notification-demo-c82e6.firebaseapp.com',
    storageBucket: 'notification-demo-c82e6.firebasestorage.app',
    measurementId: 'G-X5ZQN24V4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfpjN3AqWhnWLcFNq7Rf7YWSuYGgiCKRA',
    appId: '1:64115782291:android:c1d1e8ced60c29151d9366',
    messagingSenderId: '64115782291',
    projectId: 'notification-demo-c82e6',
    storageBucket: 'notification-demo-c82e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGBCssaLfGQJli_LjRlPHXf0Wc9DuF3FU',
    appId: '1:64115782291:ios:002ea4075013706d1d9366',
    messagingSenderId: '64115782291',
    projectId: 'notification-demo-c82e6',
    storageBucket: 'notification-demo-c82e6.firebasestorage.app',
    iosBundleId: 'com.example.notificationDemo',
  );
}
